# https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node/
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kt
  name: kt-k8s-monitoring-deployment
  labels:
    app: kt-k8s-monitoring
spec:
  selector:
    matchLabels:
      app: kt-k8s-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: kt-k8s-monitoring
    spec:
      containers:
        - name: kt-api-server
          #image: harbor.k8s.io:30082/nlu_project/kt-k8s-monitoring:latest
          image: harbor.k8s.io:30082/nlu_project/kt-k8s-monitoring:${BUILD_NUMBER}
          imagePullPolicy: Always
          env:
          - name: TZ
            value: Asia/Seoul
          - name: JAVA_TOOL_OPTIONS
            value: "-Xms2048m -Xmx4096m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /service-api # /mnt/nfs/kt-service-api-pvc-pvc-73c7efb8-3b67-4173-ae97-307505d128e4 경로가 service-api로 마운트됨.
              name: service-api-volume
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: service-api-volume
          persistentVolumeClaim:
            claimName: service-api-pvc
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
#      nodeSelector:
#        key: worker
